version: '3.7'

services:
  hub:
   image: selenium/hub:3.141.59-zinc
   ports:
     - "4444:4444"
   networks:
        - "mmfei_network_frontend"
        - "mmfei_network_backend"

  chrome:
    image: selenium/node-chrome:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
        replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    networks:
        - "mmfei_network_frontend"
        - "mmfei_network_backend"
  firefox:
    image: selenium/node-firefox:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
        replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    networks:
        - "mmfei_network_frontend"
        - "mmfei_network_backend"

networks:
  mmfei_network_frontend:
    # Use a custom driver
    # driver: mmfei-network-frontend
  mmfei_network_backend:
    # Use a custom driver which takes special options
    # driver: mmfei-network-backend
    # driver_opts:
    #   foo: "1"
    #   bar: "2"%